// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool({
  name: "list_orders",
  title: "List my orders",
  description: "List the signed-in user's orders in the Nepges Store, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of orders to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("orders").select("id, status, total, items, shipping_address, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-wishlist.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_wishlist_default = defineTool2({
  name: "list_wishlist",
  title: "List my wishlist",
  description: "List all products the signed-in user has saved to their wishlist.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("wishlists").select("id, product_handle, product_data, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-to-wishlist.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_to_wishlist_default = defineTool3({
  name: "add_to_wishlist",
  title: "Add to wishlist",
  description: "Save a product (by its store handle) to the signed-in user's wishlist.",
  inputSchema: {
    product_handle: z2.string().trim().min(1).describe("The product handle from the Nepges Store.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_handle }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("wishlists").insert({ user_id: ctx.getUserId(), product_handle }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added ${product_handle} to wishlist.` }],
      structuredContent: { row: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/get-wallet-balance.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_wallet_balance_default = defineTool4({
  name: "get_wallet_balance",
  title: "Get wallet balance",
  description: "Return the signed-in user's virtual wallet balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("wallets").select("balance, updated_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const balance = data?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Wallet balance: ${balance}` }],
      structuredContent: { balance, updated_at: data?.updated_at ?? null }
    };
  }
});

// src/lib/mcp/tools/list-wallet-transactions.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.80.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_wallet_transactions_default = defineTool5({
  name: "list_wallet_transactions",
  title: "List wallet transactions",
  description: "List the signed-in user's virtual wallet transactions, newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max transactions to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("wallet_transactions").select("id, amount, transaction_type, description, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wyyqojscsxrznsoncvcn";
var mcp_default = defineMcp({
  name: "nepges-store-mcp",
  title: "Nepges Store",
  version: "0.1.0",
  instructions: "Tools for the Nepges Store. Callers act as the signed-in shopper: view their orders, manage their wishlist, and check their virtual wallet.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_orders_default,
    list_wishlist_default,
    add_to_wishlist_default,
    get_wallet_balance_default,
    list_wallet_transactions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
